"""
ctxl init — Generate optimized .github/copilot-instructions.md

Creates a task-focused instruction file that GitHub Copilot reads natively.
Optionally integrates the codebase map to give Copilot structural awareness.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from ctxl.mapper import map_directory, format_map_output


DEFAULT_INSTRUCTIONS_TEMPLATE = """# Copilot Context Instructions
_Auto-generated by `ctxl init` on {timestamp}_

## Current Task
{task_description}

## Focus Files
{focus_files}

## Codebase Structure
{codebase_map}

## Guidelines
- Focus ONLY on the files and task described above.
- Do NOT read or modify files outside the focus list unless explicitly asked.
- Keep responses concise to preserve context window space.
- If you need to understand a function's implementation, ask — don't guess.
"""


def generate_instructions(
    project_root: str,
    task: str,
    focus_files: Optional[list] = None,
    include_map: bool = True,
    output_path: Optional[str] = None,
) -> str:
    """
    Generate a .github/copilot-instructions.md file.

    Args:
        project_root: Path to the project root directory.
        task: Description of the current task.
        focus_files: List of file paths to focus on (relative to project root).
        include_map: Whether to include the codebase skeleton map.
        output_path: Custom output path. Defaults to .github/copilot-instructions.md.

    Returns:
        The path to the generated instructions file.
    """
    root = Path(project_root).resolve()

    # Build focus files section
    if focus_files:
        focus_section = "\n".join(f"- `{f}`" for f in focus_files)
    else:
        focus_section = "_No specific focus files set. Copilot will use its default context._"

    # Build codebase map section
    if include_map:
        skeletons = map_directory(str(root))
        if skeletons:
            codebase_map = format_map_output(skeletons)
        else:
            codebase_map = "_No supported source files found for mapping._"
    else:
        codebase_map = "_Codebase map not included. Run `ctxl map` to generate one._"

    # Fill the template
    content = DEFAULT_INSTRUCTIONS_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
        task_description=task,
        focus_files=focus_section,
        codebase_map=codebase_map,
    )

    # Determine output path
    if output_path is None:
        out_dir = root / ".github"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / "copilot-instructions.md"
    else:
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)

    out_file.write_text(content, encoding="utf-8")
    return str(out_file)
